import { useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { useQueryClient } from '@tanstack/react-query'
import api from '@/shared/api/client'
import { useToastStore } from '@/shared/lib/toast'
import { getErrorMessage } from '@/shared/lib/error'

interface ResolvedKey {
  projectId: string
  projectKey: string
  issueId: string
  issueNumber: number
  title: string
}

/**
 * Global click listener that intercepts anchors auto-generated by
 * `linkifyIssueKeys`. Each anchor carries `data-issue-key="PM-123"`;
 * on click, resolve the key via `/api/issues/resolve`, then navigate
 * via React Router to the Board with `?open={issueId}` so the detail
 * panel opens.
 *
 * Mounted once at the app shell. The handler delegates from the
 * document so it catches links rendered anywhere — issue descriptions,
 * comment bodies, spec markdown, etc.
 *
 * Resolved keys are cached in TanStack Query (`['resolve-issue-key',
 * key]`) so re-opening a thread doesn't re-hit the endpoint.
 */
export function useIssueKeyLinkHandler() {
  const navigate = useNavigate()
  const queryClient = useQueryClient()

  useEffect(() => {
    function handler(event: MouseEvent) {
      // Only left-clicks without modifier keys — leave Cmd+click for
      // "open in new tab", though we still need a real URL for that to
      // make sense. (Phase 2.)
      if (event.button !== 0 || event.metaKey || event.ctrlKey || event.shiftKey) return
      const target = event.target as HTMLElement | null
      if (!target) return
      const anchor = target.closest('a[data-issue-key]') as HTMLAnchorElement | null
      if (!anchor) return
      const key = anchor.getAttribute('data-issue-key')
      if (!key) return

      event.preventDefault()
      void (async () => {
        try {
          const resolved = await queryClient.fetchQuery<ResolvedKey>({
            queryKey: ['resolve-issue-key', key],
            queryFn: () =>
              api
                .get<{ data: ResolvedKey }>(`/issues/resolve`, { params: { key } })
                .then((r) => r.data.data),
            staleTime: 5 * 60_000,
          })
          navigate(`/projects/${resolved.projectKey}/board?open=${resolved.issueId}`)
        } catch (err) {
          useToastStore
            .getState()
            .addToast(getErrorMessage(err, `Couldn't resolve ${key}`), 'error')
        }
      })()
    }

    document.addEventListener('click', handler)
    return () => document.removeEventListener('click', handler)
  }, [navigate, queryClient])
}
